<?php

namespace Tests\Feature;

use App\Models\Restaurant;
use App\Models\User;
use Database\Seeders\UserSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class CreateRestaurantTest extends TestCase {
    use RefreshDatabase;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(UserSeeder::class);
    }

    #[Test]
    public function a_user_can_create_a_restaurant() {
        $this->withoutExceptionHandling();

        $data = [
            'name' => 'Restaurant',
            'description' => 'Restaurant description',
        ];

        $user = User::find(1);
        $this->actingAsUser($user);
        $response = $this->post("{$this->apiBaseUrl}/restaurants/store", $data);

        $response->assertStatus(200);
        $response->assertJsonStructure(['message', 'data' => [
            'id', 'name', 'slug', 'description'
        ], 'status_code']);

        $restaurant = Restaurant::find(1);

        $this->assertDatabaseHas('restaurants', [
            'id' => 1,
            'user_id' => 1,
            'name' => $data['name'],
            'description' => $data['description'],
        ]);

        $this->assertStringContainsString('restaurant', $restaurant->slug);
    }

    #[Test]
    public function name_must_be_required() {
        $data = [
            'name' => '',
            'description' => 'Restaurant description',
        ];

        $user = User::find(1);
        $this->actingAsUser($user);
        $response = $this->post("{$this->apiBaseUrl}/restaurants/store", $data);

        $response->assertStatus(422);
        $response->assertJsonStructure(['message', 'status_code', 'errors' => ['name']]);
    }

    #[Test]
    public function description_must_be_required() {
        $data = [
            'name' => 'Restaurant',
            'description' => '',
        ];

        $user = User::find(1);
        $this->actingAsUser($user);
        $response = $this->post("{$this->apiBaseUrl}/restaurants/store", $data);

        $response->assertStatus(422);
        $response->assertJsonStructure(['message', 'status_code', 'errors' => ['description']]);
    }
}
